<?php
/**
 * @author         Ulpi Kans <radarier+gh@gmail.com>
 * @copyright  (c) 2016, Ulpi Kans
 * @package        Ulpi\Holidays
 * @since          2016-03-20
 * @version        0.1.0alpha (AK47)
 */


declare( strict_types = 1 );


namespace Ulpi\Holidays;


/**
 * Defines all available holiday config types
 *
 * @since v0.1.0alpha (AK47)
 */
interface HolidayType
{


   /**
    * A holiday with an static date
    */
   const STATIC       = 'static';

   /**
    * A holiday with an dynamic date, generated by an callback function
    */
   const DYNAMIC      = 'dynamic';

   /**
    * A holiday with an static base date and an difference value in relation to the base date
    */
   const STATIC_BASE  = 'static_base';

   /**
    * A holiday with an dynamic base date and an difference value in relation to the base date
    */
   const DYNAMIC_BASE = 'dynamic_base';

}

